name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: List some environment variables
        run: |
          echo "GITHUB_RUN_NUMBER = ${{ github.run_number }}"
          echo "GITHUB_ATTEMPT_NUMBER = ${{ github.run_attempt}}"
          echo "BRANCH_LEAF=`echo ${{ github.ref }} | sed 's/^.*\///'`" >> $GITHUB_ENV
      - name: Set output filename
        run: echo "BUILD_OUTPUT_FILE=`echo glove80-${{ env.BRANCH_LEAF }}-build-${{ github.run_number }}.${{ github.run_attempt }}.uf2`" >> $GITHUB_ENV
      - name: use env var
        run: |
          echo ${{ env.TAG }}
          echo ${{ env.BRANCH_LEAF }}
          echo ${{ env.BUILD_OUTPUT_FILE }}
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/checkout@v3
        with:
          repository: moergo-sc/zmk
          ref: zephyr-3-2-20230730
          path: src
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-22.05
      - uses: cachix/cachix-action@v12
        with:
          name: moergo-glove80-zmk-dev
          skipPush: true
      - name: Build Glove80 combined firmware
        run: nix-build config -o combined
      - name: Copy result out of nix store
        run: cp combined/glove80.uf2 ${{ env.BUILD_OUTPUT_FILE }}
      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BUILD_OUTPUT_FILE }}
          path: ${{ env.BUILD_OUTPUT_FILE }}
