name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: List some environment variables
        run: |
          echo "GITHUB_RUN_NUMBER = ${{ github.run_number }}"
          echo "GITHUB_ATTEMPT_NUMBER = ${{ github.run_attempt}}"
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/checkout@v3
        with:
          repository: moergo-sc/zmk
          ref: zephyr-3-2-20230730
          path: src
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-22.05
      - uses: cachix/cachix-action@v12
        with:
          name: moergo-glove80-zmk-dev
          skipPush: true
      - name: Build Glove80 combined firmware
        run: nix-build config -o combined
      - name: Copy result out of nix store
        run: cp combined/glove80.uf2 glove80.uf2
      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: glove80-${{ github.run_number }}.${{ github.run_attempt }}.zip
          path: glove80.uf2
