name: Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get the path-friendly branch name
        run: |
          echo "BRANCH_LEAF=`echo ${{ github.ref }} | sed 's/^.*\///'`" >> $GITHUB_ENV
      - name: Configure the output filename
        run: echo "BUILD_OUTPUT_FILE=`echo glove80-${{ env.BRANCH_LEAF }}-build-${{ github.run_number }}.${{ github.run_attempt }}.uf2`" >> $GITHUB_ENV
      - name: Debug env variables
        run: |
          echo "BRANCH_LEAF=$BRANCH_LEAF"
          echo "BUILD_OUTPUT_FILE=$BUILD_OUTPUT_FILE"
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/checkout@v4
        with:
          repository: moergo-sc/zmk
          ref: v24.02
          path: src
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-22.05
      - uses: cachix/cachix-action@v15
        with:
          name: moergo-glove80-zmk-dev
          skipPush: true
      - name: Build Glove80 combined firmware
        run: nix-build config -o combined
      - name: Copy result out of nix store
        run: cp combined/glove80.uf2 ${{ env.BUILD_OUTPUT_FILE }}
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_OUTPUT_FILE }}
          path: |
            ${{ env.BUILD_OUTPUT_FILE }}
            glove80.svg